In [5]:
import pandas as pd

In [12]:
df = pd.read_excel('교환학생.xlsx')

In [16]:
df

,2017-2 파견 영어권 선발내용,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,국가,대학,수학기간,선발인원,어학요건,파견대학 등록금\n(1학기),본교 학비 감면\n(1학기),숙박비\n(4개월),홈페이지,비고,NaN
1,미국,Angelo State University\n(교환 / 어학+정규),1개 학기,1,IBT 79 / IELTS 6.5,면제,0.3,"약 $4,000\n(밀플랜 포함)",www.angelo.edu,NaN,NaN
2,NaN,NaN,2개 학기,10,Option B. TOEFL IBT 50-59 / TOEIC 600-699 / IE...,"어학코스(14주): 약$5,000",0.5,NaN,www.angelo.edu/dept/elli,가을학기 14주 ESL + 정규과정,NaN
3,NaN,NaN,NaN,NaN,NaN,"정규학기: 약$4,100(15학점)",NaN,NaN,NaN,NaN,NaN
4,NaN,Arkansas State University,2개 학기,1,IBT 61/ IELTS5.5 / PBT 500,"약$3,600(12학점)",0.5,"약 $2,800",www.astate.edu,"밀플랜 약 $1,635 ; Int'l Student Fee $350/semester...",NaN
5,NaN,Black Hills State University\n(교환 / 어학+정규),2개 학기,5,IBT 61 / PBT 500 / IELTS 5.5 / TOEIC 600,면제,0.3,"약 $3,500",http://www.bhsu.edu/Admissions/Apply/Internati...,NaN,NaN
6,NaN,NaN,2개 학기,15,IBT 61 / PBT 500 / IELTS 5.5 / TOEIC 600,"어학코스(16주): $5,300",0.5,NaN,NaN,가을학기 16주 AEPP(Academic English Preparation Pro...,NaN
7,NaN,NaN,NaN,NaN,IBT 61 / PBT 500 / IELTS 5.5 / TOEIC 600,"정규학기: $5,800(15학점)",NaN,NaN,NaN,NaN,NaN
8,NaN,"University of California, San Diego",2개 학기,10,IBT 90 / IELTS 7.5 / CEFR C1,"약 $9,000(1쿼터)",0.5,"약 $3,500",www.ip.extension.ucsd.edu,기숙사 미지원(기숙사는 여름학기에만)\nTuition은 Application Fee...,NaN
9,NaN,University of Missouri Kansas City\n(교환 / 어학+정규),1개 학기,1,IBT 71 / IELTS 6.0,면제,0.3,"약 $4,000",http://info.umkc.edu/international/incoming-ex...,"Medicine, Pharmacy, Nursing, Law, Dentistry, A...",NaN
10,NaN,NaN,2개 학기,10,IBT 45 / IELTS 5.0,"어학(ESL) 약 $4,023\n정규학기 약 $4,023",0.5,NaN,www.umkc.edu/ali/,가을학기 16주 ESL + 정규과정\n(정규과정은 원하는 자에 한하여 신청 가능하...,NaN
11,NaN,University of Nebraska Kearney,2개 학기,10,IBT 61/ IELTS5.5,"약 $4,000(12학점)",0.5,"약 $3,250",www.unk.edu,기숙사비용: http://www.unk.edu/offices/reslife/hous...,NaN
12,NaN,Michigan State University,2개 학기,10,"IBT 79(단, 분야별 17 이상) / IELTS 6.5 / PBT 550 (단...","약 $11,700(12학점)",0.5,"약 $7,500",www.msu.edu,"Business (Marketing, Management, Accounting, F...",NaN
13,NaN,Northern State University,2개 학기,10,IBT 61/ IELTS 5.5,면제,0.3,비고란 참고,www.northern.edu,"수업료는 면제이나, 학점당 약 $140-$170의 수수료 납부(아래 링크 확인)\n...",NaN
14,NaN,"SUNY, Stony Brook University",1개 학기,1,IBT 80/ IELTS 6.5,면제,0.3,"약 $4,700",www.sunysb.edu/,Course List : http://sb.cc.stonybrook.edu/bull...,NaN
15,NaN,Tarleton State University,2개 학기,2,IBT 80 / IELTS 6.0,면제,0.3,"약 $2,000",http://www.tarleton.edu/,NaN,NaN
16,NaN,Thiel College,2개 학기,5,IBT 62 / IELTS 5.5,면제,0.3,"약 $3,500",www.thiel.edu/,"학생회비, 문화체험비, 시설사용비 약 $1,500 납부",NaN
17,NaN,Purdue University Northwest\n(교환 / Study Abroad),1개 학기,1,IBT 79 / IELTS 6.5 / PBT 550,면제,0.3,"약 $5,500\n(밀플랜포함)",https://banwebf.purduecal.edu/pls/proddad/WEBC...,방문학생 같은 경우 두가지 1) ELP-Bridge 2) Academic cours...,NaN
18,NaN,NaN,1개 학기,10,ELP Bridge(2 courses): PBT & ITP 527 / IBT 69 ...,"약 $7,100 (ELP-Bridge)\n약 $8,100 (15학점)",0.5,NaN,NaN,NaN,NaN
19,NaN,"University of California, River Side",2개 학기,10,IBT 79/ IELTS 6.5 / ITP 550,"약 $4,800(1쿼터)",0.5,기숙사: 비고란 참고\n홈스테이: 약 $900(1달),http://www.iep.ucr.edu/,"쿼터제로 1쿼터(약 10주)에 최대 12학점 수강\n(한 과목당 4 credit, ...",NaN
20,NaN,University of New mexico\n(교환 / 어학+정규),2개 학기,5,학부 PBT 520 / IBT 68 / IELTS 6.0\n대학원 PBT 550 /...,면제,0.3,"약 $3,200",https://studyabroad.unm.edu/exchange,NaN,NaN
21,NaN,NaN,2개 학기,5,IBT 61 / IELTS 5.5,"약 $2,600 (어학)",0.5,NaN,www.unm.edu,어학과목 2개를 필수로 들어야하며 정규학기 과목도 두개만 수강 가능함.,NaN
22,NaN,Valdosta State University,2개 학기,2,IBT 69 / IELTS 6.0,면제,0.3,"약 $ 3,300\n(밀플랜포함)",https://www.valdosta.edu/,강의List: http://www.valdosta.edu/administration...,NaN
23,NaN,"University of Wisconsin, River Falls",1개 학기,2,IBT 78/ IELTS 6.0 / PBT 547 / TOEIC 730,면제,0.3,"약 $2,500",https://www.uwrf.edu/Catalog/DegreeRequirement...,"Meal Plan $1,257/semester ; Campus Fees $800/s...",NaN
24,NaN,Dalton State College,1개 학기,1,PBT 523 / IBT 69 / IELTS 6.0,NaN,NaN,NaN,NaN,NaN,NaN
25,캐나다,University of Manitoba (어학+지역학),1개 학기,10,공인어학성적 필요 없음\n자체인터뷰,"약 CAD 5,000",0.5,"약 C$3,000",www.umanitoba.ca,"기숙사비에 식비 포함되어있음 / 문화체험비용 및 교재, 픽업, 학교 시설사용비 CA...",NaN
26,NaN,University of Ottawa,1개 학기,2,"IBT 86 (단, Writing 22) / IELTS 6.5 (단, Writing...",면제,0.3,"약 C$3,000",http://international.uottawa.ca/en/study-at-uo...,"Telfer School of Management, Faculty of Medici...",NaN
27,NaN,Mount Allison University,2개 학기,2,IBT 90 / IELTS 6.5,면제,0.3,"약 C$2,500",http://www.mta.ca/Registrars_Office/Schedules_...,음악관련학과 지원불가\nMeal plan 약 C$2500,NaN
28,브라질,University of Sao Paulo,2개 학기,2,IBT 80 / IELTS 6.5 / ITP 550,면제,0.3,"약 $2,500",www.fea.usp.br/conteudo.php?m=5,기숙사 배정이 불가능하여 Off-Campus Housing을 해야함/ 영어강의가 한...,NaN
29,아르헨티나,Universidad Argentina de La Empresa,2개 학기,1,IBT 71 (스페인어 가능자 우대) / ITP 520,면제,0.3,"약 $2,000",www.uade.edu.ar/,"기숙사 Guarantee되지 않으며, 별도의 아파트/숙소 알아보아야 할 수 있음",NaN
...,...,...,...,...,...,...,...,...,...,...,...
81,NaN,Swinburne University of Technology,2개 학기,10,IBT 78 / IELTS 6.0,"약 A$8,900 (4과목)",0.5,비고란 참고,www.swinburne.edu.au/,IELTS with no band below 5.5 ; IBT with no ban...,NaN
82,영국,University of Southampton,2개 학기,2,IBT 92 / IELTS 6.5 (1년 수학 예정자의 경우 IELTS 만 허용),면제,0.3,비고 참고,www.southampton.ac.uk,Film and Media 쪽으로만 지원가능\n숙소비용: http://www.sou...,NaN
83,NaN,"Goldsmiths College, University of London",2개 학기,10,"IELTS 6.5 (단, Writing 6.5; 각 영역별 6.0 이상)","약 £6,700",0.5,"약 ₤4,500",www.goldsmiths.ac.uk,"기입된 등록금은 평균 수준의 등록금이며, 학과마다 등록금 상이할 수 있으니 사이트 ...",NaN
84,NaN,University of Nottingham,2개 학기,5,"인문, 법, 사회과학, 심리학, 건축학, 수학: IELTS 6.5 (모든 영역 6....","약 ₤7,200",0.7,"약 ₤3,000\n비고란 참고",www.nottingham.ac.uk,NaN,NaN
85,NaN,Keele University,2개 학기,2,IELTS 6.0,면제,0.3,"약 ₤3,000\n비고란 참고",https://www.keele.ac.uk/studyabroad/studentsco...,숙소비용: https://www.keele.ac.uk/studyatkeele/acc...,NaN
86,NaN,The University of Manchester,2개 학기,5,"* 경영/경제/회계, 심리학, 생명과학 계열 TOELF 90/ IELTS 6.5\n...","약 £7,500",0.7,"약 ₤2,500",http://www.manchester.ac.uk/study/internationa...,"GPA3.5이상 지원 가능/등록금의 경우 1개학기로 파견할 경우에는 약 £6,30...",NaN
87,NaN,University of Leicester,2개 학기,5,"IBT 90/ IELTS 6.5 \n*법: 100 / IETLS7.0\n*화학, 컴...","약 ₤5,000\n*이공계열전공: 약 ₤6,500",0.5,약 ₤85~200/week,http://www2.le.ac.uk/offices/international/ove...,어학 요건 하기 사이트에서 참고할 것 \nhttp://www.nottingham.a...,NaN
88,태국,Mahidol University,2개 학기,5,IBT 61 / IELTS 5.5,면제,0.3,"약 THB 10,000",https://www.mahidol.ac.th/mugo/info_pr/Student...,NaN,NaN
89,인도,Hindustan University,2개 학기,5,IBT 61 / IELTS 5.5 / ITP 500,면제,0.3,"약 $1,500 (식비 포함)",www.hindustanuniv.ac.in,NaN,NaN
90,NaN,SRM University,1개 학기,4,IBT 61 / IELTS 5.5,면제,0.3,"약 $4,500\n(밀플랜포함)",http://www.srmuniv.ac.in/ir/inward-mobility,NaN,NaN
91,NaN,Rajagiri Business School,1개 학기,3,PBT 587 / IELTS 7.0 / TOEIC 780,면제,0.3,"약 $1,600",http://rajagiribusinessschool.com/,"Management studies, social welfare and enginee...",NaN
92,NaN,Christ University,2개 학기,2,IBT 61 / IELTS 5.5 / ITP 500 / TOEIC 750,면제,0.3,약 $600,http://www.christuniversity.in,수학기간: 11월 - 4월중순 / 6월 - 10월 중순,NaN
93,NaN,Indian Institute of Technology Bombay (IITB),2개 학기,3,"IBT 95 (단, W21이상) / IELTS 7.0 / TOEIC 780",면제,0.3,"약 $1,600",http://portal.iitb.ac.in/asc/courses,참고: http://www.ir.iitb.ac.in/wp-content/upload...,NaN
94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,* 파견대학 등록금 및 기타비용은 대학 사정에 따라 상승 혹은 하락할 수도 있음,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,"* 기숙사 및 숙소비는 종류별 금액이 상이하므로, 해당학교 2인실 1개학기 혹은 해...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,"* 기숙사비에는 Meal Plan이 포함되어 있지 않으며, 기숙사에 거주하는 학생들...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,* 표에 명기되어있는 비용 외에 그 밖에 파견대학에서 필요로하는 기타 비용이 발생할...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,* 어학요건의 경우 나열된 시험 중 한 개만 충족 시키면 됨,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,* 파견대학 상황에 따라 작년 대비 어학요건이 변경된 대학이 있을 수 있음,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,* 영국에 있는 대학교에 1년으로 지원할 학생들은 반드시 IELTS로 지원해야 하며...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,"* 표에 명기되어있는 비용 외에 교환학생 지원서 접수료, 기타 보험료, 국제학생회비...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,* 선발인원은 별도 Comment 없을 경우 6개월 교환 + 1년 교환학생을 합한 수임.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,* 반드시 비고란에 학교별 체크해야 할 사항이 있는지 확인할 것,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,* 자세한 사항은 학교별 사이트 참고할 것,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,복수학위,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,국가,대학,기간,선발인원,어학요건 및 자격요건,기관토플(ITP),파견대학 등록금(1학기),본교 학비 감면\n(1학기),기숙사비 (1학기),홈페이지,비고
110,미국,"State University of NY, Stony Brook",최소 2년,5,"IBT 80, IELTS 6.5 / 평점평균 3.5 이상",X,"약 $10,000",0.7,"약 $5,000",www.sunysb.edu/,복수학위 지원자는 방문 상담 요망

In [17]:
df2 = df.iloc[1:25]

In [23]:
df3 = df2[df2["Unnamed: 2"]==u'2개 학기']

In [25]:
df3  = df3[df3['Unnamed: 5'] == u'면제']

In [34]:
writer = pd.ExcelWriter(path='america.xlsx', engine='xlsxwriter')
df3.to_excel(writer)
writer.save()

In [33]:
df3

,2017-2 파견 영어권 선발내용,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
5,NaN,Black Hills State University\n(교환 / 어학+정규),2개 학기,5,IBT 61 / PBT 500 / IELTS 5.5 / TOEIC 600,면제,0.3,"약 $3,500",http://www.bhsu.edu/Admissions/Apply/Internati...,NaN,NaN
13,NaN,Northern State University,2개 학기,10,IBT 61/ IELTS 5.5,면제,0.3,비고란 참고,www.northern.edu,"수업료는 면제이나, 학점당 약 $140-$170의 수수료 납부(아래 링크 확인)\n...",NaN
15,NaN,Tarleton State University,2개 학기,2,IBT 80 / IELTS 6.0,면제,0.3,"약 $2,000",http://www.tarleton.edu/,NaN,NaN
16,NaN,Thiel College,2개 학기,5,IBT 62 / IELTS 5.5,면제,0.3,"약 $3,500",www.thiel.edu/,"학생회비, 문화체험비, 시설사용비 약 $1,500 납부",NaN
20,NaN,University of New mexico\n(교환 / 어학+정규),2개 학기,5,학부 PBT 520 / IBT 68 / IELTS 6.0\n대학원 PBT 550 /...,면제,0.3,"약 $3,200",https://studyabroad.unm.edu/exchange,NaN,NaN
22,NaN,Valdosta State University,2개 학기,2,IBT 69 / IELTS 6.0,면제,0.3,"약 $ 3,300\n(밀플랜포함)",https://www.valdosta.edu/,강의List: http://www.valdosta.edu/administration...,NaN