In [1]:
import pandas as pd
import sqlalchemy as sql

In [2]:
conn = sql.create_engine('mysql://zezeon:cockcodk0@localhost/csv?charset=utf8')

In [3]:
df = pd.read_sql('select * from algorithm', conn)
df.columns

Index([u'학번', u'학년', u'이름', u'핸드폰', u'이메일'], dtype='object')

In [4]:
df.head()

           학번  학년   이름            핸드폰                      이메일
0  2008111939   3  이주익  010-5688-1841        wndlrrl@naver.com
1  2011112287   0  김혁진  010-2705-7159         hj7159@naver.com
2  2011112329   0  조양규  010-8750-1432    gimmetheone@naver.com
3  2012111659   0  나선엽  010-2881-8818  billyna2001@hanmail.net
4  2012111944   0  이용호    01041415409         yh1483@naver.com

In [6]:
df[df[u'학번']>2015000000]

            학번  학년   이름            핸드폰                     이메일
25  2015112114   0  박소희    01077226585      phj99209@naver.com
26  2015112148   0  임세진  010-3634-5039     pearlcang@naver.com
27  2015112156   0  정수경    01093736828    soo_960315@naver.com
28  2015112157   0  황선영  010-5763-0808  whiteflower_@naver.com
29  2015112163   0  서소영  010-5486-6823       soy9567@naver.com
30  2015112482   0  손명희  010-6247-6121  cubemackerel@naver.com
31  2016110056   0  박승원   031-255-6698       zezeon1@gmail.com

In [9]:
df.describe()

                 학번        학년
count  3.200000e+01  32.00000
mean   2.013206e+09   0.09375
std    1.573144e+06   0.53033
min    2.008112e+09   0.00000
25%    2.012112e+09   0.00000
50%    2.013112e+09   0.00000
75%    2.014113e+09   0.00000
max    2.016110e+09   3.00000

In [8]:
pd.read_sql('describe algorithm', conn)

  Field     Type Null Key Default Extra
0    학번  int(11)  YES        None
1    학년  int(11)  YES        None
2    이름     text  YES        None
3   핸드폰     text  YES        None
4   이메일     text  YES        None

In [11]:
htmlstr = '''<table class="css_tb" border="1" cellspacing="0" cellpadding="0">
<thead>
<tr>
<th class="pattern" width="84">Pattern</th>
<th class="meaning" width="194">Meaning</th>
<th width="26">S5</th>
<th width="24">C8</th>
<th width="25">F3.6</th>
<th width="25">O11</th>
<th width="25">I9b</th>
<th width="21">I8</th>
<th width="19">I7</th>
<th width="19">I6</th>
</tr>
</thead>
<tbody>
<tr>
<th class="pattern" width="84">#id</th>
<td class="meaning" width="194">id로 지정된 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19">O</td>
</tr>
<tr>
<th class="pattern" width="84">.class</th>
<td class="meaning" width="194">class로 지정된 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19">O</td>
</tr>
<tr>
<th class="pattern" width="84">E</th>
<td class="meaning" width="194">E 요소를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19">O</td>
</tr>
<tr>
<th class="pattern" width="84">E:link</th>
<td class="meaning" width="194">방문하지 않은 E를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19">O</td>
</tr>
<tr>
<th class="pattern" width="84">E:visited</th>
<td class="meaning" width="194">방문한 E를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19">O</td>
</tr>
<tr>
<th class="pattern" width="84">E:hover</th>
<td class="meaning" width="194">마우스가 올라가 있는 동안 E를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19">O</td>
</tr>
<tr>
<th class="pattern" width="84">E:active</th>
<td class="meaning" width="194">마우스 클릭 또는 키보드(enter)가 눌린 동안 E를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:focus</th>
<td class="meaning" width="194">focus가 머물러 있는 동안 E를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:first-line</th>
<td class="meaning" width="194">E 요소의 첫 번째 라인 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:first-letter</th>
<td class="meaning" width="194">E 요소의 첫 번째 문자 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
</tbody>
<tbody class="css2">
<tr>
<th class="pattern" width="84">*</th>
<td class="meaning" width="194">모든 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19">O</td>
</tr>
<tr>
<th class="pattern" width="84">E[foo]</th>
<td class="meaning" width="194">&#8216;foo&#8217; 속성이 포함된 E를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E[foo=&#8221;bar&#8221;]</th>
<td class="meaning" width="194">&#8216;foo&#8217; 속성의 값이 &#8216;bar&#8217;와 일치하는 E를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E[foo~=&#8221;bar&#8221;]</th>
<td class="meaning" width="194">&#8216;foo&#8217; 속성의 값에 &#8216;bar&#8217;가 포함되는 E를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E[foo|=&#8221;en&#8221;]</th>
<td class="meaning" width="194">&#8216;foo&#8217; 속성의 값이 &#8216;en&#8217; 또는 &#8216;en-&#8216; 으로 시작되는  E를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:first-child</th>
<td class="meaning" width="194">첫 번째 자식 요소가 E라면 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:lang(fr)</th>
<td class="meaning" width="194">HTML lang 속성의 값이 &#8216;fr&#8217;로 지정된 E를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E::before</th>
<td class="meaning" width="194">E 요소 전에 생성된 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E::after</th>
<td class="meaning" width="194">E 요소 후에 생성된 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E&gt;F</th>
<td class="meaning" width="194">E 요소의 자식인 F 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E+F</th>
<td class="meaning" width="194">E 요소를 뒤의 F 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
</tbody>
<tbody class="css3">
<tr>
<th class="pattern" width="84">E[foo^=&#8221;bar&#8221;]</th>
<td class="meaning" width="194">&#8216;foo&#8217; 속성의 값이 &#8216;bar&#8217;로 정확하게 시작하는 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E[foo$=&#8221;bar&#8221;]</th>
<td class="meaning" width="194">&#8216;foo&#8217; 속성의 값이 &#8216;bar&#8217;로 정확하게 끝나는 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E[foo*=&#8221;bar&#8221;]</th>
<td class="meaning" width="194">&#8216;foo&#8217; 속성의 값에 &#8216;bar&#8217;를 포함하는 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:root</th>
<td class="meaning" width="194">문서의 최상위 루트 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:nth-child(n)</th>
<td class="meaning" width="194">그 부모의 n번째 자식이 앞으로부터 지정된 순서와 일치하는 E 라면 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:nth-last-child(n)</th>
<td class="meaning" width="194">n번째 자식이 뒤로부터 지정된 순서와 일치하는 요소가 E 라면 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:nth-of-type(n)</th>
<td class="meaning" width="194">E 요소 중 앞으로부터 순서가 일치하는 n번째 E 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:nth-last-of-type(n)</th>
<td class="meaning" width="194">E 요소 중 끝으로부터 순서가 일치하는 n번째 E 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:last-child</th>
<td class="meaning" width="194">E 요소 중 마지막 자식이라면 E 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:first-of-type</th>
<td class="meaning" width="194">E 요소 중 첫번째 E 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:last-of-type</th>
<td class="meaning" width="194">E 요소 중 마지막 E 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:only-child</th>
<td class="meaning" width="194">E 요소가 유일한 자식이면 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:only-of-type</th>
<td class="meaning" width="194">E 요소가 같은 타입이면 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:empty</th>
<td class="meaning" width="194">텍스트 및 공백을 포함하여 빈 자식을 가진 E를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:target</th>
<td class="meaning" width="194">E의 URI의 대상이 되면 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:enabled</th>
<td class="meaning" width="194">활성화된 폼 컨트롤 E요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:disabled</th>
<td class="meaning" width="194">비활성화된 폼 컨트롤 E요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:checked</th>
<td class="meaning" width="194">선택된 폼 컨트롤(라디오버튼,체크박스)을 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E:not(s)</th>
<td class="meaning" width="194">s가 아닌 E 요소 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
<td width="19"><span class="ns">X</span></td>
</tr>
<tr>
<th class="pattern" width="84">E~F</th>
<td class="meaning" width="194">E 요소가 앞에 존재하면 F를 선택</td>
<td width="26">O</td>
<td width="24">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="25">O</td>
<td width="21">O</td>
<td width="19">O</td>
<td width="19"><span class="ns">X</span></td>
</tr>
</tbody>
</table>'''

In [20]:
ddf = pd.read_html(htmlstr, encoding='utf-8')#dataframe의 list를 리턴한다.

In [25]:
print ddf[0].to_latex()

\begin{tabular}{lllllllllll}
\toprule
{} &         Pattern &                            Meaning & S5 & C8 & F3.6 & O11 & I9b & I8 & I7 & I6 \\
\midrule
0 &             \#id &                      id로 지정된 요소 선택 &  O &  O &    O &   O &   O &  O &  O &  O \\
1 &          .class &                   class로 지정된 요소 선택 &  O &  O &    O &   O &   O &  O &  O &  O \\
2 &               E &                           E 요소를 선택 &  O &  O &    O &   O &   O &  O &  O &  O \\
3 &          E:link &                      방문하지 않은 E를 선택 &  O &  O &    O &   O &   O &  O &  O &  O \\
4 &       E:visited &                          방문한 E를 선택 &  O &  O &    O &   O &   O &  O &  O &  O \\
5 &         E:hover &               마우스가 올라가 있는 동안 E를 선택 &  O &  O &    O &   O &   O &  O &  O &  O \\
6 &        E:active &  마우스 클릭 또는 키보드(enter)가 눌린 동안 E를 선택 &  O &  O &    O &   O &   O &  O &  O &  X \\
7 &         E:focus &             focus가 머물러 있는 동안 E를 선택 &  O &  O &    O &   O &   O &  O &  X &  X \\
8 &    E:first-line &                   E 요소의 첫 번째 라인 선택 &  O &  O &    O &   O &   O &  O &  O &  X \\
9 &  E:first-letter &                   E 요소의 첫 번째 문자 선택 &  O &  O &    O &   O &   O &  O &  O &  X \\
\bottomrule
\end{tabular}